name: ASCII85 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Build
        run: chmod +x build.sh && ./build.sh

      - name: Run tests
        run: chmod +x test.sh && ./test.sh
